-- 0001_init.sql
-- Initial schema for Siti ERP, ported from Supabase.
-- 16 tables. PKs default to `bigint generated by default as identity` to match
-- the implicit Supabase behaviour observed in the legacy DB. Two tables keep
-- their original `uuid` PKs (dough_usage, packaging_rules).

CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- for gen_random_uuid()

-- ─────────────────────────────────────────────────────────────────────────────
-- Core entities
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE ingredients (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 text NOT NULL,
    unit                 text,
    price_per_unit       numeric DEFAULT 0,
    stock_qty            numeric DEFAULT 0,
    min_stock            numeric DEFAULT 0,
    supplier_id          text,
    sku                  text,
    category             text,
    supplier             text,
    package_qty          numeric DEFAULT 1,
    package_unit         text DEFAULT 'יח',
    purchase_unit        text DEFAULT 'יח',
    purchase_unit_grams  numeric DEFAULT 1000,
    purchase_price       numeric DEFAULT 0,
    price_per_kg         numeric DEFAULT 0,
    warehouse            text DEFAULT 'raw_materials',
    sku2                 text,
    sku3                 text,
    discount_pct         numeric DEFAULT 0,
    purchase_unit_qty    numeric DEFAULT 0,
    waste_pct            numeric DEFAULT 0,
    unlimited_stock      boolean DEFAULT false,
    updated_at           timestamptz DEFAULT now()
);

CREATE TABLE ingredient_aliases (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generic_name  text NOT NULL,
    ingredient_id bigint REFERENCES ingredients(id) ON DELETE SET NULL,
    created_at    timestamptz DEFAULT now()
);
CREATE INDEX idx_ingredient_aliases_generic_name ON ingredient_aliases(generic_name);
CREATE INDEX idx_ingredient_aliases_ingredient_id ON ingredient_aliases(ingredient_id);

CREATE TABLE recipes (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            text NOT NULL,
    category        text,
    selling_price   numeric DEFAULT 0,
    yield_qty       numeric DEFAULT 1,
    yield_unit      text DEFAULT 'יח',
    ingredients     jsonb,
    target_fc_pct   numeric DEFAULT 30,
    product_type    text DEFAULT 'finished',
    created_at      timestamptz DEFAULT now()
);

CREATE TABLE suppliers (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    email       text,
    notes       text,
    created_at  timestamptz DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Production
-- ─────────────────────────────────────────────────────────────────────────────

-- Aggregated production summary (written by app on save).
CREATE TABLE production_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        date,
    worker      text,
    items       jsonb,
    created_at  timestamptz DEFAULT now()
);
CREATE INDEX idx_production_log_date ON production_log(date);

-- Raw checklist entries. NOTE: write source unknown — see db/legacy_schema.md.
CREATE TABLE production_logs (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        date,
    worker      text,
    data        jsonb,
    created_at  timestamptz DEFAULT now()
);
CREATE INDEX idx_production_logs_date ON production_logs(date);

CREATE TABLE dough_usage (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    product_name    text NOT NULL,
    dough_name      text NOT NULL,
    grams_per_unit  numeric NOT NULL,
    created_at      timestamptz DEFAULT now()
);

CREATE TABLE packaging_rules (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    category        text NOT NULL,
    product_keyword text,
    ingredient_name text NOT NULL,
    ratio           numeric NOT NULL DEFAULT 1,
    notes           text,
    created_at      timestamptz DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Sales / Labor / Expenses
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE sales_log (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date              date,
    items             jsonb,
    total_revenue     numeric DEFAULT 0,
    total_waste       numeric DEFAULT 0,
    total_discounts   numeric DEFAULT 0,
    total_cancels     numeric DEFAULT 0,
    source            text DEFAULT 'manual',
    created_at        timestamptz DEFAULT now()
);
CREATE INDEX idx_sales_log_date ON sales_log(date);

CREATE TABLE labor_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        date,
    workers     jsonb,
    total_cost  numeric DEFAULT 0,
    department  text,
    role        text,
    created_at  timestamptz DEFAULT now()
);
CREATE INDEX idx_labor_log_date ON labor_log(date);

CREATE TABLE fixed_workers (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text,
    role        text,
    salary      numeric DEFAULT 0,
    dept        text DEFAULT 'production',
    created_at  timestamptz DEFAULT now()
);

CREATE TABLE expenses (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text,
    amount      numeric DEFAULT 0,
    category    text,
    type        text DEFAULT 'fixed',
    date        date,
    created_at  timestamptz DEFAULT now()
);
CREATE INDEX idx_expenses_date ON expenses(date);

-- ─────────────────────────────────────────────────────────────────────────────
-- Purchases
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE invoices (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name     text,
    supplier_id       text,
    inv_num           text,
    invoice_number    text DEFAULT '',
    date              date,
    total             numeric,
    total_excl_vat    numeric DEFAULT 0,
    total_incl_vat    numeric DEFAULT 0,
    vat               numeric DEFAULT 0,
    total_discount    numeric DEFAULT 0,
    items             jsonb,
    has_alerts        boolean DEFAULT false,
    document_url      text,
    created_at        timestamptz DEFAULT now()
);
CREATE INDEX idx_invoices_date ON invoices(date);
CREATE INDEX idx_invoices_inv_num ON invoices(inv_num);
CREATE INDEX idx_invoices_supplier_name ON invoices(supplier_name);

CREATE TABLE purchase_orders (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name   text NOT NULL,
    status          text DEFAULT 'pending',
    notes           text,
    order_date      date NOT NULL,
    expected_date   date,
    received_date   date,
    total_amount    numeric DEFAULT 0,
    items           jsonb,
    created_at      timestamptz DEFAULT now()
);
CREATE INDEX idx_purchase_orders_status ON purchase_orders(status);
CREATE INDEX idx_purchase_orders_order_date ON purchase_orders(order_date);

CREATE TABLE scan_corrections (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            text,
    original        text,
    corrected       text,
    supplier_name   text,
    makat           text,
    created_at      timestamptz DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Inventory audits
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE stock_audits (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_date  date NOT NULL,
    items       jsonb NOT NULL,
    notes       text,
    created_at  timestamptz DEFAULT now()
);
CREATE INDEX idx_stock_audits_audit_date ON stock_audits(audit_date);
