-- 0002_pos_sku.sql
-- Add POS SKU to recipes; add pos_products catalog table.

ALTER TABLE recipes ADD COLUMN IF NOT EXISTS sku TEXT;
CREATE INDEX IF NOT EXISTS idx_recipes_sku ON recipes(sku);

CREATE TABLE IF NOT EXISTS pos_products (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku          text UNIQUE NOT NULL,
    product_name text,
    category     text,
    imported_at  timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pos_products_sku ON pos_products(sku);
