CREATE TABLE IF NOT EXISTS invoice_documents (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  bigint NOT NULL,
    filename    text,
    mimetype    text,
    data        text,
    created_at  timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_invoice_documents_invoice_id ON invoice_documents(invoice_id);
